allowBuilds:
  core-js: false
  electron: true
  electron-winstaller: true
  esbuild: true
  msw: true
  node-pty: true

supportedArchitectures:
  os:
    - current
    - darwin
  cpu:
    - x64
    - arm64

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - msw
  - node-pty
